require "frectonz.plugins"
require "frectonz.options"
require "frectonz.keymaps"
require "frectonz.colorscheme"
require "frectonz.cmp"
require "frectonz.lsp"
require "frectonz.treesitter"

require "frectonz.plugins.lualine"
require "frectonz.plugins.telescope"
require "frectonz.plugins.autopairs"
require "frectonz.plugins.comment"
require "frectonz.plugins.gitsigns"
require "frectonz.plugins.nvim-tree"
require "frectonz.plugins.bufferline"
require "frectonz.plugins.fidget"
require "frectonz.plugins.rust-tools"
